#<% require 'kitchen-sync' %>
---
driver_plugin: vagrant
driver_config:
  use_vagrant_berkshelf_plugin: true
  customize:
    memory: 2048
    cpus: 1
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
    # name: nodes
  roles_path: roles
  # require_chef_omnibus: 12.15.10
  environments_path: environments
  data_bags_path: data_bags
  #encrypted_data_bag_secret_key_path: "site-cookbooks/sb-secret/files/default/"
  cookbook_path: ["cookbooks"]
  client_rb:
    environment: local

verifier:
  name: inspec

platforms:
#  - name: ubuntu-12.04
  - name: ubuntu-14.04
#  - name: centos-6.5
#  - name: centos-6.6
#  - name: centos-7.1

suites:
###### Single servers ######
  - name: base
    run_list:
      - role[base]
    verifier:
      inspec_tests:
        - test/recipes
        - https://github.com/dev-sec/tests-os-hardening
        - https://github.com/dev-sec/tests-ssh-hardening
    attributes: {}
    nodes_path: test/nodes

  - name: nginx-server
    run_list:
      - role[base]
      - role[nginx-server]
    verifier:
      inspec_tests:
        - cookbooks/app_nginx/test/recipes
    attributes: {}
    nodes_path: test/nodes

  - name: goapp-server
    run_list:
      - role[base]
      - role[goapp-server]
    verifier:
      inspec_tests:
        - cookbooks/app_goapp/test/recipes
    attributes: {}
    nodes_path: test/nodes

###### SB binary webapp servers ######
  - name: b-server1
    driver:
      ipaddress: 192.168.33.34
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: sb-nginx-server1
    run_list:
      - role[nginx-server]
    attributes: {}
    nodes_path: test/nodes

  - name: b-server2
    driver:
      ipaddress: 192.168.33.35
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: sb-goapp-server1
    run_list:
      - role[base]
      - role[goapp-server]
    attributes: {}
    nodes_path: test/nodes

  - name: b-server3
    driver:
      ipaddress: 192.168.33.36
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: sb-goapp-server2
    run_list:
      - role[base]
      - role[goapp-server]
    attributes: {}
    nodes_path: test/nodes
